releases:
- name: cron
  version: latest

jobs:
- name: master
  properties:
    docker:
      log_options: [max-size=10m, max-file=1]
- name: minion
  properties:
    docker:
      log_options: [max-size=10m, max-file=1]
- name: apply-kubernetes-manifests
  templates:
  - {name: cron, release: cron}
  properties:
    manifests:
    - content: (( file "manifests/storage-class.yaml" ))
    - content: (( file "manifests/kube2iam.yaml" ))
      recreate: true
    - content: (( file "manifests/fluentd-cloudwatch.yaml" ))
      recreate: true
    - content: (( file "manifests/riemann-podstatus.yaml" ))
      recreate: true

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 30000-600000
  serial: true

properties:
  riemann:
    server: (( grab properties.collectd.riemann_server))
  cron:
    variables:
      AWS_DEFAULT_REGION: (( grab meta.aws.default_region ))
      S3_BUCKET_NAME: (( grab meta.etcd_bucket_name ))
    entries:
    - script:
        name: etcdbackup.sh
        contents: (( file "cronjobs/etcdbackup.sh" ))
      minute: '*/15'
      hour: '*'
      day: '*'
      month: '*'
      wday: '*'
      user: root
