jobs:
- name: apply-kubernetes-manifests
  properties:
    manifests:
    - content: (( file "manifests/storage-class.yaml" ))
    - content: (( file "manifests/kube2iam.yaml" ))
      recreate: true
    - content: (( file "manifests/fluentd-cloudwatch.yaml" ))
      recreate: true

properties:
  riemann:
    server: (( grab properties.collectd.riemann_server))
  cron:
    variables:
      AWS_DEFAULT_REGION: (( grab meta.aws.default_region ))
      S3_BUCKET_NAME: (( grab meta.etcd_bucket_name ))
    entries:
    - script:
        name: etcdbackup.sh
        contents: (( file "cronjobs/etcdbackup.sh" ))
      minute: '*/15'
      hour: '*'
      day: '*'
      month: '*'
      wday: '*'
      user: root
