---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch-v1
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd-cloudwatch
        image: (( grab meta.image ))
        env:
        - name: AWS_REGION
          value: (( grab meta.region ))
        - name: LOG_GROUP_NAME
          value: (( grab meta.log_group ))
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlogdockercontainers
          mountPath: /var/vcap/store/docker/docker/containers
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogdockercontainers
        hostPath:
          path: /var/vcap/store/docker/docker/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
