---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
      - image: jtblin/kube2iam:latest
        name: kube2iam
        args:
        - "--base-role-arn=$(BASE_ROLE_ARN)"
        - "--default-role=$(DEFAULT_ROLE)"
        - "--host-ip=$(HOST_IP)"
        - "--iptables=true"
        env:
        - name: AWS_REGION
          value: (( grab meta.region ))
        - name: BASE_ROLE_ARN
          value: (( grab meta.base_role_arn ))
        - name: DEFAULT_ROLE
          value: (( grab meta.default_role ))
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8181
          hostPort: 8181
          name: http
        securityContext:
          privileged: true
