---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: riemann-podstatus
  labels:
    app: riemann-podstatus
spec:
  template:
    metadata:
      labels:
        name: riemann-podstatus
    spec:
      hostNetwork: true
      containers:
      - image: 18fgsa/concourse-task
        name: bash
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |-
          while sleep 60; do
            /bin/bash -x <(curl -s -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/pods/ | jq -r '.items[] | "riemannc send --server '${RIEMANN_HOST}' --host riemann-podstatus --service "+.metadata.namespace+"/"+.metadata.name+" --state "+.status.phase+";"')
          done
        env:
        - name: RIEMANN_HOST
          value: (( grab meta.riemann ))
        securityContext:
          privileged: true
